version: "3.7"
services:
    main:
        container_name:  mainsd
        build: .
        image: "node:10-alpine"
        tty: true
        working_dir: /usr/app
        volumes: 
            - .:/usr/app/
        command: "npm run start:dev"
        ports:
            - 3030:3030
            - 9229:9229
        networks:
            - webnet
        depends_on:
            - postgres
    postgres:
        container_name: postgres
        image: postgres:latest
        environment: 
            - POSTGRES_USER=todo
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=todo
        volumes:
            - ./db/initdb.sh:/docker-entrypoint-initdb.sh
        ports:
            - '5445:5432'
        networks:
            - webnet
networks:
    webnet:
volumes:
    pgdata: