version: "3.7"
services:
    main:
        container_name:  mainsd
        build:
            context: .
            target: development
        environment:
            DEBUG: 'true'
        tty: true
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        command: npm start:dev
        depends_on:
            - postgres
        networks:
            - webnet
    postgres:
        container_name: postgres
        image: postgres:latest
        environment: 
            - POSTGRES_USER=todo
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=todo
        volumes:
            - ./db/initdb.sh:/docker-entrypoint-initdb.sh
        ports:
            - '5445:5432'
        networks:
            - webnet
networks:
    webnet:
volumes:
    pgdata: