version: "3.7"
services:
    main:
        container_name: app-nest
        build: .
        image: "node:12"
        tty: true
        working_dir: /usr/app
        volumes: 
            - .:/usr/app/
        command: "npm run start:dev"
        ports:
            - 3000:3000