version: "3.7"
services:
    postgres:
        container_name: postgres-docker
        image: postgres:latest
        restart: always
        ports:
            - 5436:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=test
        volumes:
            - /srv/docker/postgresql:/var/lib/postgresqls