version: "3.7"
services:
    main:
        container_name:  mainsd
        build: .
        image: "node:10-alpine"
        tty: true
        working_dir: /usr/app
        volumes: 
            - .:/usr/app/
        command: "npm run start:dev"
        ports:
            - 3000:3000
        networks:
            - webnet
        depends_on:
            - postgres
    postgres:
        container_name: postgres
        image: postgres:latest
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=test
        ports:
            - '5432:5432'
        volumes:
            - ./db/initdb.sh:/docker-entrypoint-initdb.sh
        networks:
            - webnet
networks:
    webnet:
volumes:
    pgdata: